export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_KEY = "SET_SEARCH_KEY";
export const SET_SELECTED_ARTICLE = "SET_SELECTED_ARTICLE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SHOW_SHIMMERS = "SHOW_SHIMMERS";
export const SET_SERVICE_UNAVAILABLE = "SET_SERVICE_UNAVAILABLE";
